---
strategy: static
no_screen_padding: 'no'
dark_mode: 'no'
static_data: '{}'
polling_verb: get
polling_url: ''
polling_headers: ''
polling_body: ''
id: 209377
custom_fields:
- keyname: year
  field_type: number
  placeholder: '2025'
  name: Year
  description: Which year that we will show the weeks
- keyname: firstDay
  field_type: select
  name: Start week on?
  description: The week should start on a Sunday or Monday?
  options:
  - 'Sunday'
  - 'Monday'
  default: 'Sunday'
- keyname: Icon
  field_type: boolean
  name: Use Icon instead?
  description: Will show a square and a cross-square instead of boxes
  default: false
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  category: "productivity,personal"
  description: Visualize your year at a glance. This plugin displays the current week number and all weeks of the year as checkboxes, marking each week as it passes to help you stay aware of time and progress through the year. Created by Guilherme based on Jasper's recipe <a href="https://usetrmnl.com/recipes/22415">Your Life in Weeks</a>. You can find me on <a href="https://dotnet.social/@Gui">Mastodon</a>, or @glmsharp on Discord or send an email. Version 1.1 (2025-01-10)
  github_url: https://github.com/GuilhermeMorais/trmnl-weeksOfYear
  email_address: gui.lopes@gmail.com
name: Weeks of the Year
refresh_interval: 1440
